properties:
  name:
    type: string
    minLength: 2
    maxLength: 30

  barcode:
    type: string
    maxLength: 13
    minLength: 12

  description:
    type: string
    maxLength: 400

  cost:
    type: number
    minimum: 0

  price:
    type: number
    minimum: 0

  quantity:
    type: integer
    minimum: 0

relations:
  category:
    target: Category
    type: ManyToMany
    views:
      name:
        as: category

required:
  - name
  - cost
  - price
  - quantity

unique:
  - name

searchable:
  - name
  - description
  - category
