/** Generated by @techbir/gen:entity */

import { Field, Input, IDInput } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { User } from './../user';
@Input()
export class CreateMessageInput {
  @Field({
    name: 'message',
    type: 'string',
    minLength: 0,
    maxLength: 500,
    required: true,
  })
  message!: string;
  @Field({
    type: 'ManyToOne',
    onDelete: 'CASCADE',
    join: true,
    eager: true,
    name: 'to',
    target: IDInput,
  })
  to?: IDInput;
  @Field({
    type: 'ManyToOne',
    onDelete: 'CASCADE',
    join: true,
    eager: true,
    name: 'from',
    target: IDInput,
  })
  from?: IDInput;
}
