/** Generated by @techbir/gen:entity */

import { CreateMessageInput } from './create-message.input.graph';
import { PartialType } from '@nestjs/graphql';
import { Input } from '@techbir/core';

@Input()
export class UpdateMessageInput extends PartialType(CreateMessageInput) {}
