/** Generated by @techbir/gen:entity */

import { Field, Input, IDInput } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { Role } from './../role';
@Input()
export class CreateUserInput {
  @Field({
    name: 'username',
    type: 'string',
    minLength: 3,
    maxLength: 30,
    required: true,
    unique: true,
  })
  username!: string;
  @Field({
    name: 'password',
    type: 'string',
    format: 'password',
    required: true,
  })
  password!: string;
  @Field({
    type: 'ManyToMany',
    eager: true,
    join: true,
    name: 'roles',
    target: IDInput,
  })
  roles?: IDInput[];
}
