/** Generated by @techbir/gen:entity */

import { CreateUserInput } from './create-user.input.graph';
import { PartialType } from '@nestjs/graphql';
import { Input } from '@techbir/core';

@Input()
export class UpdateUserInput extends PartialType(CreateUserInput) {}
