/** Generated by @techbir/gen:entity */

import { Dto, Property, IDDto } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { PriceLevel } from './../price-level';
@Dto()
export class CreateStoreDto {
  @Property({
    autocomplete: 'off',
    icon: 'info',
    inputType: 'text',
    label: 'Name',
    maxLength: 30,
    minLength: 3,
    name: 'name',
    required: true,
    type: 'string',
    unique: true,
  })
  name!: string;
  @Property({
    type: 'ManyToMany',
    eager: true,
    join: true,
    name: 'priceLevel',
    target: IDDto,
  })
  priceLevel?: IDDto[];
}
