/** Generated by @techbir/gen:entity */

import { PartialType } from '@nestjs/swagger';
import { Dto } from '@techbir/core';
import { CreateStoreDto } from './create-store.dto';

@Dto()
export class UpdateStoreDto extends PartialType(CreateStoreDto) {}
