/** Generated by @techbir/gen:entity */

import { CreateGroupInput } from './create-group.input.graph';
import { PartialType } from '@nestjs/graphql';
import { Input } from '@techbir/core';

@Input()
export class UpdateGroupInput extends PartialType(CreateGroupInput) {}
