properties:
  name:
    type: String
    inputType: text
    minLength: 3
    maxLength: 20
    unique: true

  description:
    type: String
    inputType: textarea
    maxLength: 400
    required: false

  upc:
    type: String
    inputType: text
    unique: true
    barcode: true

  price:
    type: Number
    inputType: currency
    minimum: 0

  cost:
    type: Number
    inputType: currency
    minimum: 0

  quantity:
    type: Integer
    inputType: integer
    minimum: 0

relations:
  category:
    type: ManyToOne
    target: category
    inputType: find-one
    eager: true
    nullable: true
    viewColumns:
      name:
        type: String
        as: category
