/** Generated by @techbir/gen:entity */

import { Dto, Property, IDDto } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { User } from './../user';
@Dto()
export class CreateMessageDto {
  @Property({
    name: 'message',
    type: 'string',
    minLength: 0,
    maxLength: 500,
    required: true,
    inputType: 'textarea',
    autocomplete: 'off',
    icon: 'message',
    label: 'Message',
  })
  message!: string;
  @Property({
    type: 'ManyToOne',
    onDelete: 'CASCADE',
    join: true,
    eager: true,
    name: 'to',
    target: IDDto,
  })
  to?: IDDto;
  @Property({
    type: 'ManyToOne',
    onDelete: 'CASCADE',
    join: true,
    eager: true,
    name: 'from',
    target: IDDto,
  })
  from?: IDDto;
}
