/** Generated by @techbir/gen:entity */

import { Entity, Column, Relation, BaseEntity } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { User } from './../user';
@Entity()
export class Message extends BaseEntity {
  @Column({
    name: 'message',
    type: 'string',
    minLength: 0,
    maxLength: 500,
    required: true,
    inputType: 'textarea',
    autocomplete: 'off',
    icon: 'message',
    label: 'Message',
  })
  message!: string;
  @Relation({
    type: 'ManyToOne',
    onDelete: 'CASCADE',
    join: true,
    eager: true,
    name: 'to',
    target: User,
  })
  to?: User;
  @Relation({
    type: 'ManyToOne',
    onDelete: 'CASCADE',
    join: true,
    eager: true,
    name: 'from',
    target: User,
  })
  from?: User;
}
