/** Generated by @techbir/gen:entity */

import { PartialType } from '@nestjs/swagger';
import { Dto } from '@techbir/core';
import { CreateMessageDto } from './create-message.dto';

@Dto()
export class UpdateMessageDto extends PartialType(CreateMessageDto) {}
