/** Generated by @techbir/gen:entity */

import { Field, Input, IDInput } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { Product } from './../product';
import { PriceLevel } from './../price-level';
@Input()
export class CreatePriceInput {
  @Field({
    defaultValue: 0,
    icon: 'attach_money',
    inputType: 'number',
    label: 'Price',
    maximum: 9007199254740991,
    minimum: 0,
    name: 'price',
    type: 'number',
  })
  price?: number = 0;
  @Field({
    defaultValue: 0,
    icon: 'money_off',
    inputType: 'number',
    label: 'Cost',
    maximum: 9007199254740991,
    minimum: 0,
    name: 'cost',
    type: 'number',
  })
  cost?: number = 0;
  @Field({
    type: 'ManyToOne',
    onDelete: 'CASCADE',
    join: true,
    eager: true,
    name: 'product',
    target: IDInput,
  })
  product?: IDInput;
  @Field({
    type: 'ManyToOne',
    onDelete: 'CASCADE',
    join: true,
    eager: true,
    name: 'priceLevel',
    target: IDInput,
  })
  priceLevel?: IDInput;
}
