/** Generated by @techbir/gen:entity */

import { Field, Input, IDInput } from '@techbir/core';

@Input()
export class CreateRoleInput {
  @Field({
    name: 'name',
    type: 'string',
    minLength: 3,
    maxLength: 30,
    required: true,
    unique: true,
  })
  name!: string;
  @Field({
    type: 'ManyToMany',
    eager: true,
    join: true,
    name: 'permissions',
    target: IDInput,
  })
  permissions?: IDInput[];
}
