properties:
  name:
    type: string
    column:
      type: text
      nullable: true

    validations:
      type: string
      maxLength: 50

  message:
    type: string
    column:
      type: text
      nullable: true

    validations:
      type: string
      maxLength: 400

  checked:
    type: boolean
    column:
      type: boolean
      nullable: true

    validations:
      type: boolean

relations:
  users:
    type: ManyToMany
    target: User
    join: true
    options:
      nullable: true

views:
  - target: User
    parent: Profile
    viewFields:
      id:
        type: number
