properties:
  name:
    type: text
    inputType: text
    minLenght: 100
    maxLength: 10
    icon: name
    default: ''

  price:
    type: numeric
    inputType: currency
    prefix: currency
    icon: currency
    minimum: 0
    default: 0

  cost:
    type: numeric
    inputType: currency
    prefix: currency
    icon: currency
    minimum: 0
    default: 0

  quantity:
    type: numeric
    inputType: currency
    icon: number
    minimum: 0
    default: 0

relations:
  category:
    icon: category
    target: Category
    type: many-to-one
    eager: true
    inputType: find-one
    view:
      name:
        as: category

unique:
  - name

required:
  - name
  - price
  - cost
  - quantity
