properties:
  firstName:
    type: string
    column:
      type: text
    validations:
      type: string
      maxLength: 50
      required: true

  lastName:
    type: string
    column:
      type: text
    validations:
      type: string
      maxLength: 50
      required: true

relations:
  user:
    type: OneToOne
    target: User
    join: true

views:
  - target: User
    parent: Profile
    viewFields:
      id:
        type: number
