properties:
  username:
    type: string
    column:
      type: text
      unique: true
    validations:
      type: string
      format: email
      required: true

  password:
    type: string
    column:
      type: text
    validations:
      type: string
      format: password
      required: true

relations:
  roles:
    type: ManyToMany
    target: Role
    join: true
    options:
      nullable: true
      eager: true

views:
  - target: Role
    parent: User
    viewFields:
      name:
        type: string
