properties:
  comment:
    type: text-md

relations:
  employee:
    type: ManyToOne
    target: Employee
    views:
      id:
        as: eid
        label: Employee id

      firstName:
        as: firstName
        label: First Name

      lastName:
        as: lastName
        label: Last Name

  task:
    type: ManyToOne
    target: Task
    eager: true
    onDelete: CASCADE
    views:
      id:
        as: taskId
        label: Task id

required:
  - comment
  - employee
  - task
