properties:
  name:
    type: text-sm
    label: Product Name

  price:
    type: number-positive
    label: Unit Price
    prefix: CURRENCY

  cost:
    type: number-positive
    label: Unit Cost
    prefix: CURRENCY

  quantity:
    type: integer-positive
    label: Quantity

  barcode:
    type: barcode
    label: Barcode

relations:
  category:
    target: Category
    eager: true
    type: ManyToOne
    views:
      name:
        as: category
        label: Category
        type: string

  department:
    target: Department
    eager: true
    type: ManyToOne
    views:
      name:
        as: department
        label: Department
        type: string

required:
  - name
  - price
  - cost
  - quantity
  - barcode
  - category
  - department

unique:
  - name
  - barcode

formGroup:
  Product:
    - name
    - barcode
    - category
    - department

  Price:
    - price
    - cost

  Quantity:
    - quantity
