/** Generated by @techbir/gen:entity */

import { Field, Input, IDInput } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { PriceLevel } from './../price-level';
@Input()
export class CreateStoreInput {
  @Field({
    autocomplete: 'off',
    icon: 'info',
    inputType: 'text',
    label: 'Name',
    maxLength: 30,
    minLength: 3,
    name: 'name',
    required: true,
    type: 'string',
    unique: true,
  })
  name!: string;
  @Field({
    type: 'ManyToMany',
    eager: true,
    join: true,
    name: 'priceLevel',
    target: IDInput,
  })
  priceLevel?: IDInput[];
}
