/** Generated by @techbir/gen:entity */

import { Field, ObjectType, Input, BaseInput } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { PriceLevel } from './../price-level';
@ObjectType()
export class Store extends BaseInput {
  @Field({
    name: 'name',
    type: 'string',
    minLength: 3,
    maxLength: 30,
    required: true,
    unique: true,
  })
  name!: string;
  @Field({
    type: 'ManyToMany',
    eager: true,
    join: true,
    name: 'priceLevel',
    target: PriceLevel,
  })
  priceLevel?: PriceLevel[];
}
