/** Generated by @techbir/gen:entity */

import { Field, ObjectType, Input, BaseInput } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
@ObjectType()
export class Feature extends BaseInput {
  @Field({
    name: 'name',
    type: 'string',
    minLength: 3,
    maxLength: 30,
    required: true,
    unique: true,
  })
  name!: string;
  @Field({ name: 'value', type: 'string', minLength: 3, maxLength: 400 })
  value?: string;
}
