/** Generated by @techbir/gen:entity */

import { CreateFeatureInput } from './create-feature.input.graph';
import { PartialType } from '@nestjs/graphql';
import { Input } from '@techbir/core';

@Input()
export class UpdateFeatureInput extends PartialType(CreateFeatureInput) {}
