// @index('./*/**.ts', f => `export * from '${f.path}'`)
export * from './category/category-form.component'
export * from './department/department-form.component'
export * from './feature/feature-form.component'
export * from './group/group-form.component'
export * from './message/message-form.component'
export * from './permission/permission-form.component'
export * from './price-level/price-level-form.component'
export * from './price/price-form.component'
export * from './product/product-form.component'
export * from './role/role-form.component'
export * from './store/store-form.component'
export * from './user/user-form.component'
