/** Generated by @techbir/gen:entity */

import { PartialType } from '@nestjs/swagger';
import { Dto } from '@techbir/core';
import { CreatePermissionDto } from './create-permission.dto';

@Dto()
export class UpdatePermissionDto extends PartialType(CreatePermissionDto) {}
