/** Generated by @techbir/gen:entity */

import { PartialType } from '@nestjs/swagger';
import { Dto } from '@techbir/core';
import { CreateDepartmentDto } from './create-department.dto';

@Dto()
export class UpdateDepartmentDto extends PartialType(CreateDepartmentDto) {}
