openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3333/api

paths:
  /product:
    summary: Get all products
  /category:
    summary: Get all categories
components:
  schemas:
    Category:
      $ref: '#/components/schemas/SinglePropertySchema'

    Store:
      $ref: '#/components/schemas/SinglePropertySchema'

    PriceLevel:
      $ref: '#/components/schemas/SinglePropertySchema'

    Price:
      properties:
        id:
          type: number
          format: id

        name:
          type: string
          uniqueItems: true

        price:
          type: number
          minimum: 0

        const:
          type: number
          minimum: 0

      required:
        - name
        - price
        - cost

    Quantity:
      properties:
        id:
          type: number
          format: id

        quantity:
          type: number

        store:
          $ref: '#/components/schemas/Store'

        product:
          $ref: '#/components/schemas/Product'

      required:
        - quantity
        - product
        - store

    Product:
      properties:
        name:
          type: string
          maxLength: 30
        category:
          type: string
          items:
            $ref: '#/components/schemas/Category'

      required:
        - name

    SinglePropertySchema:
      properties:
        id:
          type: number
        name:
          type: string
          uniqueItems: true
      required:
        - name
