type: basic-resource
mainProperty: name
properties:
  name:
    type: string

  description:
    type: string

  category:
    type: many-to-one
    target: category

required:
  - name

unique:
  - name

group:
  primary:
    - name
    - description

  meta:
    - category

rest:
  get:
    product:
      description: Get products
      params:
        take:
          type: number
          in: query
          description: |
            Get the specified number of products.
            If take query param does not exit, the defult value, 20, is used.
            If take value is more than 50, the maximum value 50 is used.
          required: true
          default: 20
          max: 50

        skip:
          type: number
          in: query
          description: |
            Skip the specified number of products.
            For example, product list contains 20 items, and you want to take the last 5 products, then set the skip 15.
          required: true
          default: 0
          min: 0

        order:
          type: string
          in: query
          description: |
            Order the list of product by the specified property name and directions (asc | desc).
            For example, you want to order the product by their name descendingly, and age ascendingly,
            Then set the order to name:desc,age:asc.
            Example:
                order=name:asc, age:desc, city:asc

    product/:id:
      params:
        id:
