properties:
  name:
    type: name

  description:
    type: description

  barcode:
    type: ean

  price:
    type: currency

  cost:
    type: currency

  quantity:
    type: integer

relations:
  category:
    type: one-to-one
    target: Category
    eager: true
    views:
      name:
        type: string
        as: category

unique:
  - name

required:
  - name
  - description
  - price
  - cost
  - quantity
