/** Generated by @techbir/gen:entity */

import { Dto, Property, IDDto } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { Role } from './../role';
@Dto()
export class CreateUserDto {
  @Property({
    name: 'username',
    type: 'string',
    minLength: 3,
    maxLength: 30,
    required: true,
    unique: true,
  })
  username!: string;
  @Property({
    name: 'password',
    type: 'string',
    format: 'password',
    required: true,
  })
  password!: string;
  @Property({
    type: 'ManyToMany',
    eager: true,
    join: true,
    name: 'roles',
    target: IDDto,
  })
  roles?: IDDto[];
}
