/** Generated by @techbir/gen:entity */

import { PartialType } from '@nestjs/swagger';
import { Dto } from '@techbir/core';
import { CreateUserDto } from './create-user.dto';

@Dto()
export class UpdateUserDto extends PartialType(CreateUserDto) {}
