/** Generated by @techbir/gen:entity */

import { Entity, Column, Relation, BaseEntity } from '@techbir/core';

import { Role } from './../role';
@Entity()
export class User extends BaseEntity {
  @Column({
    name: 'username',
    type: 'string',
    minLength: 3,
    maxLength: 30,
    required: true,
    unique: true,
  })
  username!: string;
  @Column({
    name: 'password',
    type: 'string',
    format: 'password',
    required: true,
  })
  password!: string;
  @Relation({
    type: 'ManyToMany',
    eager: true,
    join: true,
    name: 'roles',
    target: Role,
  })
  roles?: Role[];
}
