/** Generated by @techbir/gen:entity */

import { Entity, Column, Relation, BaseEntity } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { Role } from './../role';
@Entity()
export class User extends BaseEntity {
  @Column({
    autocomplete: 'username',
    format: 'email',
    icon: 'person',
    inputType: 'text',
    label: 'Username',
    name: 'username',
    required: true,
    type: 'string',
    unique: true,
  })
  username!: string;
  @Column({
    name: 'password',
    type: 'string',
    format: 'password',
    required: true,
    autocomplete: 'current-password',
    inputType: 'password',
    icon: 'password',
    label: 'Password',
    hash: true,
  })
  password!: string;
  @Relation({
    type: 'ManyToMany',
    eager: true,
    join: true,
    name: 'roles',
    target: Role,
  })
  roles?: Role[];
}
