/** Generated by @techbir/gen:entity */

import { Dto, Property, IDDto } from '@techbir/core';
import { PartialType } from '@nestjs/graphql';
import { Permission } from './../permission';
@Dto()
export class CreateRoleDto {
  @Property({
    name: 'name',
    type: 'string',
    minLength: 3,
    maxLength: 30,
    required: true,
    unique: true,
  })
  name!: string;
  @Property({
    type: 'ManyToMany',
    eager: true,
    join: true,
    name: 'permissions',
    target: IDDto,
  })
  permissions?: IDDto[];
}
