/** Generated by @techbir/gen:entity */

import { CreateDepartmentInput } from './create-department.input.graph';
import { PartialType } from '@nestjs/graphql';
import { Input } from '@techbir/core';

@Input()
export class UpdateDepartmentInput extends PartialType(CreateDepartmentInput) {}
