/** Generated by @techbir/gen:entity */

import { PartialType } from '@nestjs/swagger';
import { Dto } from '@techbir/core';
import { CreateFeatureDto } from './create-feature.dto';

@Dto()
export class UpdateFeatureDto extends PartialType(CreateFeatureDto) {}
