properties:
  name:
    type: String

  description:
    type: String

  category:
    type: ManyToOne
    target: category
    eager: true
    viewColumns:
      name:
        as: category

  tags:
    type: ManyToMany
    target: tag
